apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "solver.fullname" . }}-frontend
  labels:
    {{- include "solver.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image.frontend }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "solver.fullname" . }}-frontend
  labels:
    {{- include "solver.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: http
      name: http
