#!/usr/bin/env bash
# OAAS O04: render a digest-pinned Compose override from local images.
#
# Usage:
#   bash scripts/render-digest-compose.sh [outfile]
#
# Prefers RepoDigest when the image was pulled/pushed; falls back to the
# local image Id (sha256:…) so offline builds without a registry still pin.
# The result is meant for:
#   docker compose -f docker-compose.yml -f <outfile> up -d --no-build
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/deploy/compose/docker-compose.digests.yml}"

pin() {
  local tag="$1"
  local digest
  digest="$(docker image inspect --format '{{index .RepoDigests 0}}' "$tag" 2>/dev/null || true)"
  if [[ -n "$digest" && "$digest" == *"@sha256:"* ]]; then
    # RepoDigest is already "name@sha256:…"
    echo "$digest"
    return 0
  fi
  local id
  id="$(docker image inspect --format '{{.Id}}' "$tag")"
  # Id is "sha256:…"; Compose accepts "tag@sha256:…"
  local hash="${id#sha256:}"
  # Keep a stable name prefix for humans; digest is what pins.
  local name="${tag%%:*}"
  echo "${name}@sha256:${hash}"
}

need() {
  local tag="$1"
  if ! docker image inspect "$tag" >/dev/null 2>&1; then
    echo "missing image: $tag (build or pull it first)" >&2
    exit 1
  fi
}

need "solver-backend:latest"
need "solver-frontend:latest"
need "postgis/postgis:16-3.4"
need "clickhouse/clickhouse-server:24.8"

BACKEND="$(pin solver-backend:latest)"
FRONTEND="$(pin solver-frontend:latest)"
POSTGRES="$(pin postgis/postgis:16-3.4)"
CLICKHOUSE="$(pin clickhouse/clickhouse-server:24.8)"

mkdir -p "$(dirname "$OUT")"
cat >"$OUT" <<EOF
# Generated by scripts/render-digest-compose.sh (OAAS O04). Do not edit by hand —
# regenerate after rebuilding images. Use with:
#   docker compose -f docker-compose.yml -f $OUT up -d --no-build
#
# pull_policy: never — images must already be present (docker load on an
# isolated host).

services:
  postgres:
    image: ${POSTGRES}
    pull_policy: never

  clickhouse:
    image: ${CLICKHOUSE}
    pull_policy: never

  backend:
    image: ${BACKEND}
    pull_policy: never

  worker:
    image: ${BACKEND}
    pull_policy: never

  frontend:
    image: ${FRONTEND}
    pull_policy: never
EOF

echo "Wrote $OUT"
echo "  postgres:    $POSTGRES"
echo "  clickhouse:  $CLICKHOUSE"
echo "  backend/worker: $BACKEND"
echo "  frontend:    $FRONTEND"
